import {
  Home, Users, UserRound, Activity, HeartPulse, FlaskConical, FileText, Search, ClipboardCheck,
  Gauge, Stethoscope, History, Upload, Settings, Database, Plug, LineChart, ShieldCheck, Rocket, ListChecks,
} from "lucide-react";

export const navByRole = {
  operator: [
    { to: "/operator/home", label: "Home", icon: Home },
    { to: "/operator/search", label: "Patient Search", icon: Search },
    { to: "/operator/pre-session", label: "Pre-Session Review", icon: ClipboardCheck },
    { to: "/operator/current-session", label: "Current Session", icon: Activity },
    { to: "/operator/history", label: "Patient History", icon: History },
    { to: "/operator/vascular", label: "Vascular Access", icon: HeartPulse },
    { to: "/operator/machine-insights", label: "Machine Insights", icon: Gauge },
    { to: "/operator/procedure-support", label: "Procedure Support", icon: ListChecks },
    { to: "/operator/reports", label: "Session Reports", icon: FileText },
  ],
  doctor: [
    { to: "/doctor/home", label: "Home", icon: Home },
    { to: "/doctor/patients", label: "Patients", icon: Users },
    { to: "/doctor/patient-360", label: "Patient 360°", icon: UserRound },
    { to: "/doctor/clinical-history", label: "Clinical History", icon: Stethoscope },
    { to: "/doctor/dialysis-history", label: "Dialysis History", icon: History },
    { to: "/doctor/vascular", label: "Vascular Access", icon: HeartPulse },
    { to: "/doctor/core-analysis", label: "Core Analysis", icon: LineChart },
    { to: "/doctor/reports", label: "Reports", icon: FileText },
    { to: "/doctor/clinical-review", label: "Clinical Review", icon: ShieldCheck },
  ],
  patient: [
    { to: "/patient/home", label: "Home", icon: Home },
    { to: "/patient/my-health", label: "My Health", icon: HeartPulse },
    { to: "/patient/upload", label: "Upload Data", icon: Upload },
    { to: "/patient/reports", label: "My Reports", icon: FileText },
    { to: "/patient/dialysis-overview", label: "Dialysis Overview", icon: Activity },
    { to: "/patient/medical-history", label: "Medical History", icon: History },
    { to: "/patient/profile", label: "Profile", icon: UserRound },
  ],
  admin: [
    { to: "/admin/home", label: "Home", icon: Home },
    { to: "/admin/users", label: "Users & Profiles", icon: Users },
    { to: "/admin/patients", label: "Patients", icon: UserRound },
    { to: "/admin/doctors", label: "Doctors", icon: Stethoscope },
    { to: "/admin/operators", label: "Operators", icon: Activity },
    { to: "/admin/ingestion", label: "Data Ingestion", icon: Database },
    { to: "/admin/integration", label: "Data Integration", icon: Plug },
    { to: "/admin/historical", label: "Historical Data", icon: History },
    { to: "/admin/machine-insights", label: "Machine Insights", icon: Gauge },
    { to: "/admin/reports", label: "Reports", icon: FileText },
    { to: "/admin/settings", label: "Settings", icon: Settings },
  ],
};

export const commonNav = [{ to: "/roadmap", label: "Future Roadmap", icon: Rocket }];

export const pageTitles = {
  "/operator/home": ["Operator", "Home"],
  "/operator/search": ["Operator", "Patient Search"],
  "/operator/pre-session": ["Operator", "Pre-Session Review"],
  "/operator/current-session": ["Operator", "Current Session"],
  "/operator/history": ["Operator", "Patient History"],
  "/operator/vascular": ["Operator", "Vascular Access"],
  "/operator/machine-insights": ["Operator", "Machine Insights"],
  "/operator/procedure-support": ["Operator", "Procedure Support"],
  "/operator/reports": ["Operator", "Session Reports"],
  "/doctor/home": ["Doctor", "Home"],
  "/doctor/patients": ["Doctor", "Patients"],
  "/doctor/patient-360": ["Doctor", "Patient 360°"],
  "/doctor/clinical-history": ["Doctor", "Clinical History"],
  "/doctor/dialysis-history": ["Doctor", "Dialysis History"],
  "/doctor/vascular": ["Doctor", "Vascular Access"],
  "/doctor/core-analysis": ["Doctor", "Core Analysis"],
  "/doctor/reports": ["Doctor", "Reports"],
  "/doctor/clinical-review": ["Doctor", "Clinical Review"],
  "/patient/home": ["Patient", "Home"],
  "/patient/my-health": ["Patient", "My Health"],
  "/patient/upload": ["Patient", "Upload Data"],
  "/patient/reports": ["Patient", "My Reports"],
  "/patient/dialysis-overview": ["Patient", "Dialysis Overview"],
  "/patient/medical-history": ["Patient", "Medical History"],
  "/patient/profile": ["Patient", "Profile"],
  "/admin/home": ["Admin", "Home"],
  "/admin/users": ["Admin", "Users & Profiles"],
  "/admin/patients": ["Admin", "Patients"],
  "/admin/doctors": ["Admin", "Doctors"],
  "/admin/operators": ["Admin", "Operators"],
  "/admin/ingestion": ["Admin", "Data Ingestion"],
  "/admin/integration": ["Admin", "Data Integration"],
  "/admin/historical": ["Admin", "Historical Data"],
  "/admin/machine-insights": ["Admin", "Machine Insights"],
  "/admin/reports": ["Admin", "Reports"],
  "/admin/settings": ["Admin", "Settings"],
  "/roadmap": ["Platform", "Future Roadmap"],
};

export const roleIcons = { operator: Activity, doctor: Stethoscope, patient: UserRound, admin: Settings, labs: FlaskConical };
