import { AlertTriangle, Info, CircleAlert, ClipboardCheck, Stethoscope, FlaskConical, FileText, Building2 } from "lucide-react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, BarChart, Bar } from "recharts";
import { Panel, Metric, TrendBadge } from "@/components/Bits";
import { levelColor, lastN } from "@/lib/engine";

const sevIcon = { high: AlertTriangle, moderate: CircleAlert, info: Info };

export default function OverviewTab({ patient, insight, onOpenTab }) {
  const recent = lastN(patient.sessions, 8);
  const chartData = recent.map((s) => ({
    name: `#${s.sessionNo}`,
    qb: s.bloodFlow,
    uf: s.ufAchieved,
    sbp: Number(s.preBP.split("/")[0]),
    vp: s.venousPressure,
  }));
  const lab = patient.labs[0];
  const last = patient.sessions[patient.sessions.length - 1];

  return (
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
      <Panel
        testId="attention-points-panel"
        title="Attention Points"
        hint="Generated by the Phase-1 rule engine from history, labs and access records. Decision support only."
        className="xl:col-span-2 xl:row-span-2"
      >
        <ul className="space-y-3" data-testid="attention-list">
          {insight.attention.map((a, i) => {
            const Icon = sevIcon[a.severity] || Info;
            return (
              <li key={i} data-testid={`attention-item-${i}`} className={`rounded-md border p-4 ${levelColor(a.severity)}`}>
                <div className="flex items-start gap-3">
                  <Icon className="h-4 w-4 mt-0.5 shrink-0" />
                  <div className="min-w-0">
                    <p className="font-semibold text-sm">{a.title}</p>
                    <p className="text-sm mt-1 opacity-90">{a.detail}</p>
                    <p className="overline mt-2 opacity-70">{a.tag}</p>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </Panel>

      <Panel
        testId="current-session-panel"
        title={`Current Session #${patient.nextSessionNo}`}
        hint={`${new Date().toDateString()} · ${patient.schedule}`}
      >
        <div className="grid grid-cols-2 gap-4">
          <Metric label="Prescribed Qb" value={patient.prescription.bloodFlow} unit="mL/min" testId="rx-qb" />
          <Metric label="Prescribed Qd" value={patient.prescription.dialysateFlow} unit="mL/min" />
          <Metric label="Duration" value={patient.prescription.durationMin} unit="min" />
          <Metric label="UF target" value={patient.prescription.ufTargetL} unit="L" />
          <Metric label="Dialysate Na / K" value={`${patient.prescription.dialysateNa}/${patient.prescription.dialysateK}`} />
          <Metric label="Dialyser" value={patient.prescription.dialyser} />
        </div>
        <p className="text-xs text-slate-500 mt-4 flex items-start gap-1.5">
          <ClipboardCheck className="h-3.5 w-3.5 mt-0.5" />
          Prescription verified by {patient.prescription.verifiedBy} on {patient.prescription.verifiedOn}
        </p>
      </Panel>

      <Panel
        testId="vascular-summary-panel"
        title="Vascular Access"
        right={<TrendBadge direction={insight.vascularTrend.direction} pct={insight.vascularTrend.pct} />}
      >
        <div className={`rounded-md border p-3 mb-4 ${levelColor(insight.accessStatus.level)}`}>
          <p className="text-sm font-semibold">{patient.vascular.type} · {patient.vascular.side}</p>
          <p className="text-sm mt-1">{patient.vascular.currentCondition}</p>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <Metric label="Site" value={patient.vascular.site} />
          <Metric label="Access age" value={patient.vascular.accessAgeMonths} unit="mo" />
          <Metric label="Last flow" value={patient.vascular.lastFlowMlMin} unit="mL/min" sub={patient.vascular.lastFlowDate} tone={patient.vascular.lastFlowMlMin < 600 ? "alert" : "ok"} />
          <Metric label="Last intervention" value={patient.vascular.lastIntervention} />
          <Metric label="Historical access events" value={insight.stats.accessEvents} />
          <Metric label="Recent cannulation events" value={insight.stats.recentAccessEvents} tone={insight.stats.recentAccessEvents ? "warn" : "ok"} />
        </div>
        <button
          data-testid="open-vascular-tab-btn"
          onClick={() => onOpenTab("vascular")}
          className="mt-4 text-sm font-semibold text-blue-700 hover:text-blue-800 transition-colors"
        >
          View vascular access timeline →
        </button>
      </Panel>

      <Panel testId="recent-dialysis-panel" title="Recent Dialysis" hint={`Last ${recent.length} sessions · machine parameters and trends`} className="xl:col-span-2">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <p className="overline mb-2">Blood flow (mL/min) &amp; venous pressure (mmHg)</p>
            <div className="h-44">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ top: 5, right: 8, left: -18, bottom: 0 }}>
                  <CartesianGrid stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} stroke="#94a3b8" />
                  <YAxis tick={{ fontSize: 10 }} stroke="#94a3b8" />
                  <Tooltip contentStyle={{ fontSize: 12, borderRadius: 6 }} />
                  <Line type="monotone" dataKey="qb" stroke="#2563eb" strokeWidth={2} dot={false} name="Qb" />
                  <Line type="monotone" dataKey="vp" stroke="#dc2626" strokeWidth={2} dot={false} name="Venous P" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div>
            <p className="overline mb-2">Ultrafiltration achieved (L) &amp; pre-dialysis systolic BP</p>
            <div className="h-44">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 5, right: 8, left: -18, bottom: 0 }}>
                  <CartesianGrid stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} stroke="#94a3b8" />
                  <YAxis tick={{ fontSize: 10 }} stroke="#94a3b8" />
                  <Tooltip contentStyle={{ fontSize: 12, borderRadius: 6 }} />
                  <Bar dataKey="uf" fill="#10b981" name="UF (L)" radius={[2, 2, 0, 0]} />
                  <Bar dataKey="sbp" fill="#f59e0b" name="Pre SBP" radius={[2, 2, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        <div className="mt-5 overflow-x-auto">
          <table className="w-full text-sm" data-testid="recent-sessions-table">
            <thead>
              <tr className="text-left border-b border-slate-200">
                {["Session", "Date", "Qb", "UF tgt/ach", "Pre BP", "Venous P", "Outcome"].map((h) => (
                  <th key={h} className="overline py-2 pr-4 whitespace-nowrap">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[...recent].reverse().map((s) => (
                <tr key={s.sessionNo} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                  <td className="metric-num py-2.5 pr-4">#{s.sessionNo}</td>
                  <td className="py-2.5 pr-4 whitespace-nowrap">{s.date}</td>
                  <td className="metric-num py-2.5 pr-4">{s.bloodFlow}</td>
                  <td className="metric-num py-2.5 pr-4">{s.ufTarget}/{s.ufAchieved}</td>
                  <td className="metric-num py-2.5 pr-4">{s.preBP}</td>
                  <td className="metric-num py-2.5 pr-4">{s.venousPressure}</td>
                  <td className="py-2.5 pr-4">
                    {s.complications.length ? (
                      <span className="text-xs font-semibold text-red-700">{s.complications.join(", ")}</span>
                    ) : (
                      <span className="text-xs text-emerald-700 font-semibold">Uneventful</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      <Panel testId="clinical-evidence-panel" title="Clinical Evidence" hint="Latest labs, prescriptions, documents and hospital events">
        <p className="overline flex items-center gap-1.5"><FlaskConical className="h-3.5 w-3.5" /> Latest labs · {lab.date}</p>
        <div className="grid grid-cols-2 gap-4 mt-3">
          <Metric label="Haemoglobin" value={lab.hb} unit="g/dL" tone={lab.hb < 10 ? "warn" : "ok"} />
          <Metric label="Potassium" value={lab.potassium} unit="mmol/L" tone={lab.potassium >= 5.5 ? "alert" : "ok"} />
          <Metric label="Creatinine" value={lab.creatinine} unit="mg/dL" />
          <Metric label="Kt/V" value={lab.ktv} tone={lab.ktv < 1.2 ? "alert" : "ok"} sub={`URR ${lab.urr}%`} />
        </div>

        <p className="overline flex items-center gap-1.5 mt-6"><Building2 className="h-3.5 w-3.5" /> Recent clinical events</p>
        <ul className="mt-2 space-y-2">
          {patient.hospitalizations.slice(0, 2).map((h, i) => (
            <li key={i} className="text-sm text-slate-700">
              <span className="metric-num text-xs text-slate-500">{h.date}</span> · {h.reason} ({h.days} d, {h.unit})
            </li>
          ))}
        </ul>

        <p className="overline flex items-center gap-1.5 mt-6"><FileText className="h-3.5 w-3.5" /> Uploaded documents</p>
        <ul className="mt-2 space-y-1.5">
          {patient.documents.slice(0, 3).map((d, i) => (
            <li key={i} className="text-sm text-blue-700 truncate">{d.name} <span className="text-xs text-slate-500">· {d.type}</span></li>
          ))}
        </ul>

        <p className="overline flex items-center gap-1.5 mt-6"><Stethoscope className="h-3.5 w-3.5" /> Latest clinical note</p>
        <p className="text-sm text-slate-700 mt-2">{patient.notes[0].text}</p>
        <p className="text-xs text-slate-500 mt-1">{patient.notes[0].by} · {patient.notes[0].date}</p>

        <button
          data-testid="open-history-tab-btn"
          onClick={() => onOpenTab("history")}
          className="mt-5 text-sm font-semibold text-blue-700 hover:text-blue-800 transition-colors"
        >
          Open full historical evidence →
        </button>
      </Panel>
    </div>
  );
}
